# Generated by Django 6.1 on 2026-08-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_can_develop_customuser_can_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='can_user',
            new_name='can_manage_user',
        ),
    ]
