# Generated by Django 6.1 on 2026-08-12 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_can_user_customuser_can_manage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
