# Generated by Django 6.1 on 2026-08-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_develop', '可开发')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '用户通知', 'verbose_name_plural': '用户通知'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_develop',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_manage_user',
        ),
    ]
