# Generated by Django 6.1 on 2026-08-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options_customuser_can_develop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='need_email_active',
            field=models.BooleanField(default=False, verbose_name='等待邮箱激活'),
        ),
    ]
