# Generated by Django 6.1 on 2026-08-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_need_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban_IP',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP 地址:')),
                ('reason', models.TextField(verbose_name='封禁理由:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='封禁发起时间:')),
                ('active', models.BooleanField(default=True, verbose_name='启用封禁')),
            ],
        ),
    ]
