# Generated by Django 6.1 on 2026-08-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_ban_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban_ip',
            options={'verbose_name': '封禁IP', 'verbose_name_plural': '封禁IP列表'},
        ),
    ]
