# Generated by Django 6.1 on 2026-08-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_ban_ip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban_ip',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封禁过期时间(留空=永久)'),
        ),
    ]
