# Generated by Django 6.1 on 2026-09-13 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_pagevisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'verbose_name': '页面访问', 'verbose_name_plural': '页面访问'},
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='path',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='统计日期'),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='today_count',
            field=models.PositiveIntegerField(default=0, verbose_name='今日次数'),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='累计次数'),
        ),
    ]
