# Generated by Django 6.1 on 2026-10-03 08:22

from django.db import migrations, models


def create_default_group(apps, schema_editor):
    """初始化一个「默认分组」，新注册用户会自动加入其中。"""
    UserGroup = apps.get_model('users', 'UserGroup')
    UserGroup.objects.get_or_create(name='默认分组', defaults={'is_default': True})


def remove_default_group(apps, schema_editor):
    UserGroup = apps.get_model('users', 'UserGroup')
    UserGroup.objects.filter(name='默认分组').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_notification_options_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_default',
            field=models.BooleanField(default=False, help_text='勾选后，新注册用户自动加入该分组', verbose_name='默认分组'),
        ),
        migrations.RunPython(create_default_group, remove_default_group),
    ]
