# Generated by Django 6.1 on 2026-10-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usergroup_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='访问量')),
            ],
            options={
                'verbose_name': '每日访问',
                'verbose_name_plural': '每日访问',
                'ordering': ['-date'],
            },
        ),
    ]
