"""
Django settings for wjw2 project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

LOCAL_RUNNING = os.getenv('LOCAL_RUNNING')=='True'

DEBUG = True
ALLOWED_HOSTS = ["localhost","127.0.0.1","wujiawei36.pythonanywhere.com"]
if not LOCAL_RUNNING:
    DEBUG = False
    ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'users',
    'panel',
    'index',
    'hijack',  # 核心功能
    'hijack.contrib.admin',  # (可选) 在Admin中集成劫持按钮[reference:12]
    # 'axes'
]

MIDDLEWARE = [
	'users.middleware.IPBlockMiddleware',
	'users.middleware.RequestBlockingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.SessionInfoMiddleware',
    'hijack.middleware.HijackUserMiddleware',  # 处理劫持会话[reference:13]
    # 'axes.middleware.AxesMiddleware',  # 添加这一行，放在最后
]

ROOT_URLCONF = 'wjw2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processor.global_site_name',
            ],
        },
    },
]

WSGI_APPLICATION = 'wjw2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# MAILERS = {
#     'default': {
#         'BACKEND': 'django.core.mail.backends.console.EmailBackend',
#         "OPTIONS": {
#             "host": "smtp.163.com",
#             "use_tls": True,
#             "username": os.environ["EMAIL_ACCOUNT_ID"],
#             "password": os.environ["EMAIL_API_KEY"],
#         },
#     },
# }

AUTH_USER_MODEL = 'users.CustomUser'

# 用于获取用户真实ip(而非本地转发的127.0.0.1)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')  # 收件人看到的发件人

# captcha
CAPTCHA_LENGTH = 4
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
CAPTCHA_TIMEOUT = 5  # 5分钟过期
CAPTCHA_NOISE_FUNCTIONS = (
	# 设置样式
	'captcha.helpers.noise_null',
	# 设置干扰线
	# 'captcha.helpers.noise_arcs',
	# 设置干扰点
	'captcha.helpers.noise_dots',
)
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
CAPTCHA_FOREGROUND_COLOR = '#000000'

SITE_NAME = 'wujiawei的网站'

LOGIN_URL='/user/login'

STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')

DEVELOPERS=[os.getenv('DEVELOPER_1')]

# AUTHENTICATION_BACKENDS = [
#     'axes.backends.AxesStandaloneBackend',  # 添加这一行，放在最前面
#     'django.contrib.auth.backends.ModelBackend',  # 原有的保留
# ]

# # 使用你自己的 IP 获取函数
# AXES_CLIENT_IP_CALLABLE = 'utils.get_ip.get_ip'

# # ====== 封锁配置 ======
# AXES_LOCK_OUT_AT_FAILURE = True          # 达到失败次数后封锁
# AXES_FAILURE_LIMIT = 5                    # 允许失败 5 次
# AXES_COOLOFF_TIME = 15                    # 封锁 15 分钟（单位：分钟）

# # 封锁策略：按 IP 封锁（默认）
# # 也可以改为按用户名封锁，或组合封锁
# AXES_LOCKOUT_PARAMETERS = ["ip_address"]
