# Generated by Django 6.1 on 2026-09-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='wjw2_live_', editable=False, max_length=16)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(help_text='用途备注，如「自己的脚本」', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='取消勾选即吊销')),
                ('expires_at', models.DateTimeField(blank=True, help_text='过期时间（空=永不过期）', null=True)),
                ('quota', models.PositiveIntegerField(blank=True, help_text='调用额度上限（空=不限）', null=True)),
                ('used', models.PositiveIntegerField(default=0, help_text='已使用次数')),
                ('allowed_slugs', models.TextField(blank=True, default='', help_text='允许的工具 slug，逗号分隔（空=全部）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='归属用户（可空）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Key',
                'ordering': ['-created_at'],
            },
        ),
    ]
