# Generated by Django 6.1 on 2026-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='rate_per_minute',
            field=models.PositiveIntegerField(blank=True, help_text='频率上限(次/分钟)：留空=跟随工具默认；0=不限频；正整数=覆盖工具默认', null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='勾选后该 Key 不受额度和频率限制（无限次使用）'),
        ),
    ]
