# Generated by Django 6.1 on 2026-09-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_apikey_rate_per_minute_apikey_unlimited'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('today_count', models.PositiveIntegerField(default=0, verbose_name='今日次数')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='累计次数')),
            ],
            options={
                'verbose_name': 'API 请求计数',
                'verbose_name_plural': 'API 请求计数',
            },
        ),
    ]
