# Generated by Django 6.1 on 2026-10-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_apirequestcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='rate_limited_count',
            field=models.PositiveIntegerField(default=0, help_text='触发限频次数'),
        ),
    ]
